# Generated by Django 3.1.2 on 2020-11-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='datetime',
            new_name='datatime',
        ),
    ]
