# Generated by Django 3.1.2 on 2020-11-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201102_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='datatime2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title2',
        ),
        migrations.AlterField(
            model_name='question',
            name='datatime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Момент_публикации'),
        ),
    ]
