# Generated by Django 3.1.2 on 2020-11-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201102_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
