# Generated by Django 3.1.2 on 2020-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201102_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
